name: Create Draft Release for Brave-Based Browsertrix Browser Base
on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build x86 and ARM Images and push to Dockerhub
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v3
        with:
          lfs: true
      -
        name: Read brave-version.txt
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./brave-version.txt
      -
        name: Set env var with brave-version
        id: set-browser-version
        run: echo "BRAVE_VERSION=${{ steps.package.outputs.content }}" >> $GITHUB_ENV
      -
        name: Create draft release on GitHub if doesn't exist
        uses: ncipollo/release-action@v1
        with:
          draft: true
          allowUpdates: true
          tag: brave-${{ env.BRAVE_VERSION }}
          body: "This release publishes the image: `webrecorder/browsertrix-browser-base:brave-${{ env.BRAVE_VERSION }}`\n\nThe image is hosted [on DockerHub](https://hub.docker.com/r/webrecorder/browsertrix-browser-base/tags?name=brave-${{ env.BRAVE_VERSION }})"
